webapp/controllers/blog.py
from flask import render_template, redirect, url_for, session, g, abort, Blueprint, flash, request

from webapp.forms import CommentForm, PostForm, SearchForm
from webapp.models import db, User, Post, Tag, Comment, tags, Photo
from sqlalchemy import func
from flask_login import login_required, current_user
from flask_principal import Permission, UserNeed
from webapp.extensions import poster_permission, admin_permission

from datetime import datetime
from sqlalchemy.sql import or_

def sidebar_data():
    recent = Post.query.order_by(Post.publish_date.desc()).limit(5).all()
    top_tags = db.session.query(Tag, func.count(tags.c.post_id).label('total')).join(tags).group_by(Tag).order_by(
        'total DESC').limit(5).all()
    return recent, top_tags


blog_blueprint = Blueprint(
    'blog',
    __name__,
    template_folder='../templates/blog',
    url_prefix="/blog"
)


@blog_blueprint.before_request
def before_request():
    g.search_form = SearchForm()
    g.tags = Tag.query.limit(20).all()
    g.is_login = hasattr(current_user, 'id')  # 是否登录


@blog_blueprint.errorhandler(404)
def page_not_found(error):
    return "404错误"


@blog_blueprint.errorhandler(403)
def page_not_found(error):
    return "你没有权限"


@blog_blueprint.route('/home')
def home():
    posts = Post.query.order_by(Post.publish_date.desc()).filter(Post.status==0).limit(20).all()
    return render_template('home.html', posts=posts)


@blog_blueprint.route('/admin')
def admin():
    if g.user is None:
        abort(403)
    return render_template('admin.html')


@blog_blueprint.route('/new/<string:type>', methods=['GET', 'POST'])
@login_required
def new(type):
    form = PostForm()
    if form.validate_on_submit():
        new_post = Post(form.title.data)
        new_post.text = form.text.data
        new_post.cover = form.cover.data
        new_post.publish_date = datetime.now()
        new_post.update_date = new_post.publish_date
        new_post.user_id = current_user.id
        new_post.type = type
        new_post.summary = form.summary.data
        new_post.video = form.video.data
        tagStrList = form.tags.data.split(',')
        for tagStr in tagStrList:
            tagStr = tagStr.strip()
            tag = Tag.query.filter_by(title=tagStr).first()
            if not tag:
                tag = Tag(tagStr)
            new_post.tags.append(tag)

        for photo_url in form.photos.data:
            if photo_url != '':
                photo = Photo(photo_url)
                new_post.photos.append(photo)

        db.session.add(new_post)
        db.session.commit()
        return redirect(url_for('blog.post', post_id=new_post.id))
    form.type.data = type
    return render_template("edit_{}.html".format(type), form=form, type=type)

@blog_blueprint.route('/edit/<int:id>', methods=['GET', 'POST'])
@login_required
@poster_permission.require(http_exception=403)
def edit(id):
    post = Post.query.get_or_404(id)
    permission = Permission(UserNeed(post.user.id))
    if permission.can() or admin_permission.can():
        form = PostForm()
        if form.validate_on_submit():
            post.title = form.title.data
            post.cover = form.cover.data
            post.video = form.video.data
            post.summary = form.summary.data
            post.text = form.text.data
            post.update_date = datetime.now()
            del post.tags[:]  # 删除所有标签
            del post.photos[:]  # 删除所有图片

            if form.tags.data.strip():
                tagStrList = form.tags.data.split(',')
                for tagStr in tagStrList:  # 对标签循环
                    tagStr = tagStr.strip()
                    tag = Tag.query.filter_by(title=tagStr).first()
                    if not tag:  # 标签不存在时新增
                        tag = Tag(tagStr)
                    post.tags.append(tag)

            for photo_url in form.photos.data:
                if photo_url != '':
                    photo = Photo(photo_url)
                    post.photos.append(photo)

            db.session.add(post)
            db.session.commit()
            return redirect(url_for('.post', post_id=post.id))
        type = post.type
        form.cover.data = post.cover
        form.text.data = post.text
        form.title.data = post.title
        form.summary.data = post.summary
        form.type.data = type
        photos = [photo.url for photo in post.photos]
        form.summary.data = post.summary
        tags = []
        for tag in post.tags:
            tags.append(tag.title)
        form.tags.data = ','.join(tags)

        return render_template("edit_{}.html".format(type), form=form, post=post, photos=photos)
    abort(403)


@blog_blueprint.route('/post/<int:post_id>', methods=['GET', 'POST'])
def post(post_id):
    form = CommentForm()
    if form.validate_on_submit():
        new_comment = Comment()
        new_comment.name = form.name.data
        new_comment.text = form.text.data
        new_comment.post_id = post_id
        new_comment.date = datetime.now()
        db.session.add(new_comment)
        db.session.commit()
        return redirect(url_for('.post', post_id=post_id))
    post = Post.query.get_or_404(post_id)
    # 添加阅读量
    post.read = post.read + 1
    db.session.add(post)
    db.session.commit()

    tags = post.tags
    comments = post.comments.order_by(Comment.date.desc()).all()
    # 是否有编辑权限
    permission = Permission(UserNeed(post.user.id))
    is_edit = permission.can() or admin_permission.can()
    if g.is_login:
        form.name.data = current_user.username
    return render_template('post.html',
                           post=post,
                           tags=tags,
                           is_edit=is_edit,
                           comments=comments,
                           form=form)


@blog_blueprint.route('/search', methods=['GET', 'POST'])
def search():
    form = g.search_form
    if form.validate_on_submit():
        posts = Post.query.filter(Post.status==0,Post.title.ilike("%{}%".format(form.keyword.data))).all()
        return render_template('search.html', posts=posts)
    return redirect(url_for('blog.home'))


@blog_blueprint.route('/tag/<int:id>', methods=['GET'])
def tag(id):
    tag = Tag.query.get_or_404(id)
    posts = tag.posts.filter(Post.status==0).all()
    return render_template('search.html', posts=posts)


@blog_blueprint.route('/list/<string:type>/<string:order>/<int:count>/<int:page>', methods=['GET'])
def list(type, order, count, page):
    if type=="all":
        pageData = Post.query.order_by(getattr(Post, order).desc()).filter(Post.status==0).paginate(page, count)
    else:
        pageData = Post.query.order_by(getattr(Post,order).desc()).filter(Post.status==0,Post.type==type).paginate(page, count)
    return render_template('list.html', type=type,order=order,page=pageData, count=count)

@blog_blueprint.route('/user_posts/<int:userid>/<string:type>/<string:order>/<int:count>/<int:page>', methods=['GET'])
def user_posts(userid,type, order, count, page):
    if type=="all":
        pageData = Post.query.order_by(getattr(Post, order).desc()).filter(Post.status==0,Post.user_id==userid).paginate(page, count)
    else:
        pageData = Post.query.order_by(getattr(Post,order).desc()).filter(Post.status==0,Post.type==type,Post.user_id==userid).paginate(page, count)
    user=User.query.filter_by(id=userid).first()
    return render_template('user_posts.html', type=type,order=order,page=pageData, count=count ,user=user)

webapp/controllers/main.py
from flask import Blueprint, flash, redirect, render_template, url_for,current_app
from webapp.extensions import oid
from webapp.forms import LoginForm, RegisterForm,OpenIDForm,UserSettingForm
from webapp.models import db, User
from flask_login import login_user,logout_user,login_required,current_user
from flask_principal import (Identity,AnonymousIdentity,identity_changed)

main_blueprint = Blueprint(
    'main',
    __name__,
    template_folder='../templates/main'
)


@main_blueprint.route('/')
def index():
    return '首页'


@main_blueprint.route('/login', methods=['GET', 'POST'])
@oid.loginhandler
def login():
    form = LoginForm()
    openid_form = OpenIDForm()
    if openid_form.validate_on_submit():
        return oid.try_login(
            openid_form.openid.data,
            ask_for=['nickname','email'],
            ask_for_optional=['fullname']
        )

    if form.validate_on_submit():
        user=User.query.filter_by(username=form.username.data).first()
        login_user(user,remember=form.remember.data)

        identity_changed.send(
            current_app._get_current_object(),
            identity=Identity(user.id)
        )
        flash("登录成功!", category="success")
        return redirect(url_for('blog.home'))

    openid_errors=oid.fetch_error()
    if openid_errors:
        flash(openid_errors,category="danger")
    form.remember.data=True
    return render_template('login.html', form=form,openid_form=openid_form)


@main_blueprint.route('/logout', methods=['GET', 'POST'])
def logout():
    logout_user()
    identity_changed.send(
        current_app._get_current_object(),
        identity=AnonymousIdentity()
    )
    flash("你已注销!", category="success")
    return redirect(url_for('blog.home'))


@main_blueprint.route('/register', methods=['GET', 'POST'])
@oid.loginhandler
def register():
    form = RegisterForm()
    openid_form=OpenIDForm()
    if openid_form.validate_on_submit():
        return oid.try_login(
            openid_form.openid.data,
            ask_for=['nickname','email'],
            ask_for_optional=['fullname']
        )
    if form.validate_on_submit():
        new_user = User()
        new_user.username = form.username.data
        new_user.nickname = form.nickname.data
        new_user.sex = form.sex.data
        new_user.set_password(form.password.data)
        db.session.add(new_user)
        db.session.commit()
        flash("注册成功，请登录！", category="success")
        return redirect(url_for('.login'))

    openid_errors=oid.fetch_error()
    if openid_errors:
        flash(openid_errors,category="danger")

    return render_template('register.html', form=form , openid_form=openid_form)


@main_blueprint.route('/user_setting', methods=['GET', 'POST'])
@login_required
def user_setting():
    form = UserSettingForm()
    user=current_user
    if form.validate_on_submit():
        user.nickname=form.nickname.data
        user.sex=form.sex.data
        user.head=form.head.data
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('blog.home'))
    form.sex.default=user.sex
    form.process()
    form.nickname.data=user.nickname
    form.head.data=user.head
    return render_template('user_setting.html', form=form )

webapp/templates/blog/admin.html
{% extends "blog/base.html" %}
{% block title %}Home{% endblock %}
{% block body %}
    这是后台
{% endblock %}

webapp/templates/blog/article.html
{% macro post(post,is_edit) %}
    {% if post.type=='photo' %}
        {{ photo(post,is_edit) }}
    {% elif post.type=='video' %}
        {{ video(post,is_edit) }}
    {% elif post.type=='article' %}
        {{ article(post,is_edit) }}
    {% endif %}
{% endmacro %}

{% macro article(post,is_edit) %}
    <div>
        <h2>{{ post.title }}</h2>
        <small>{{ post.publish_date.strftime('%Y-%m-%d %H:%M:%S') }} {{ userLink(post.user.id,post.user.username) }}</small>
        {% if is_edit %}
            <a href="{{ url_for('blog.edit',id=post.id) }}">编辑</a>
        {% endif %}
        <p><img src="{{ post.cover }}"></p>
        <p>{{ post.text | safe }}</p>
        <div>
            tag:
            {% for tag in post.tags %}
                <a href="{{ url_for('blog.tag',id=tag.id) }}">{{ tag.title }}</a>
            {% endfor %}
        </div>
    </div>
{% endmacro %}

{% macro photo(post,is_edit) %}
    <div>
        <h2>{{ post.title }}</h2>
        <small>{{ post.publish_date.strftime('%Y-%m-%d %H:%M:%S') }} {{ userLink(post.user.id,post.user.username) }}</small>
        {% if is_edit %}
            <a href="{{ url_for('blog.edit',id=post.id) }}">编辑</a>
        {% endif %}
        <div class="card">
            <div class="card-body">
                <p class="card-text">{{ post.summary }}</p>
            </div>
        </div>

        {% for photo in post.photos %}
            <img src="{{ photo.url }}">
        {% endfor %}

        <div>
            tag:
            {% for tag in post.tags %}
                <a href="{{ url_for('blog.tag',id=tag.id) }}">{{ tag.title }}</a>
            {% endfor %}
        </div>
    </div>
{% endmacro %}

{% macro video(post,is_edit) %}
    <div>
    <video src="{{ post.video }}" width="100%" controls="controls"></video>
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">{{ post.title }}</h4>
            <small>{{ post.publish_date.strftime('%Y-%m-%d %H:%M:%S') }} {{ userLink(post.user.id,post.user.username) }}</small>
            <p class="card-text">{{ post.summary }}</p>

            {% if is_edit %}
                <a href="{{ url_for('blog.edit',id=post.id) }}" class="btn btn-primary">编辑</a>
            {% endif %}
        </div>
    </div>
    <div>
    tag:
        {% for tag in post.tags %}
            <a href="{{ url_for('blog.tag',id=tag.id) }}">{{ tag.title }}</a>
        {% endfor %}
    </div>
{% endmacro %}


{% macro articleList(posts) %}
    <div class="card-columns">
        {% for post in posts %}
            {{ articleItem(post) }}
        {% endfor %}
    </div>
{% endmacro %}

{% macro articleItem(post) %}
    <div class="card">

        {% if post.type=='photo' and post.cover %}
            <a href="{{ url_for('.post',post_id=post.id) }}"><img class="card-img-top" src="{{ post.cover }}"></a>
        {% elif post.type=='video' and post.cover %}
            <a href="{{ url_for('.post',post_id=post.id) }}"><img class="card-img-top" src="{{ post.cover }}"></a>
        {% endif %}

        <div class="card-body">
            <h2>{{ post.title }}</h2>
            <small>
                {{ userLink(post.user.id,post.user.username) }}
                发布于：{{ post.publish_date.strftime('%Y-%m-%d %H:%M:%S') }}</small>
            <p class="card-text">{{ post.summary | safe | truncate(200) }}</p>
            <p><a class="uk-button uk-button-text" href="{{ url_for('.post',post_id=post.id) }}">查看</a></p>
        </div>
    </div>
{% endmacro %}

{% macro userLink(userid,username) %}
    <a href="{{ url_for('blog.user_posts',userid=userid,type='all',order='publish_date',count=10,page=1) }}">{{ username }}</a>
{% endmacro %}

webapp/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Blog{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"
          integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://cdn.bootcss.com/popper.js/1.12.3/umd/popper.min.js"
            integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh"
            crossorigin="anonymous"></script>
    <script src="https://cdn.bootcss.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
            integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="/static/public.css">
</head>
<body>
<header class="navbar navbar-dark bg-dark navbar-expand-lg bd-navbar">
    <div class="container">
        <a class="navbar-brand" href="{{ url_for('blog.home') }}">青风藤</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('blog.home') }}">首页</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('blog.list',order='publish_date',type='all',count=10,page=1) }}">列表</a>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        发布
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{{ url_for('blog.new',type='article') }}">文章</a>
                        <a class="dropdown-item" href="{{ url_for('blog.new',type='photo') }}">图片</a>
                        <a class="dropdown-item" href="{{ url_for('blog.new',type='video') }}">视频</a>
                    </div>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0" action="{{ url_for('blog.search') }}" method="POST">
                {{ g.search_form.hidden_tag() }}
                {{ g.search_form.keyword(class="form-control mr-sm-2") }}
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索</button>
            </form>

            {% if g.is_login %}
                <ul class="navbar-nav ml-3">
                    <li class="nav-item dropdown">
                        <a class="btn btn-sm btn-secondary dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ current_user.nickname or current_user.username }}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ url_for('main.user_setting') }}">设置</a>

                            {% if g.is_login %}
                                <a class="dropdown-item" href="{{ url_for('main.logout') }}">注销</a>
                            {% else %}
                                <a class="dropdown-item" href="{{ url_for('main.login') }}">登陆</a>
                            {% endif %}
                        </div>
                    </li>
                </ul>
            {% else %}
                <ul class="navbar-nav ml-3">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.login') }}">登陆</a>
                    </li>
                </ul>
            {% endif %}

        </div>
    </div>
</header>

<div class="container">
    <div class="row flex-xl-nowrap">
        <div class=" d-xl-block col-12 col-xl-3 bd-toc py-md-2">
            {# {% if g.is_login %}
                <div class="card bg-light">
                    <div class="card-body">
                        <div class="d-flex flex-row">
                            <img src="{{ current_user.head }}" class="rounded" width="60px" height="60px">
                            <div class="pl-2">
                                <div>{{ current_user.nickname }}水岸东方
                                    <small>{{ current_user.username }}</small>
                                </div>
                            </div>
                        </div>
                        <div>
                            <a href="#" class="btn btn-primary btn-sm mt-2">设置</a>
                            <a href="#" class="btn btn-light btn-sm mt-2">注销</a>
                        </div>
                    </div>
                </div>
            {% endif %}#}

            <div class="widget">
                <h4 class="title">标签</h4>
                <div class="content tag-cloud">
                    {% for tag in g.tags %}
                        <a class="btn btn-outline-info btn-sm m-1"  href="{{ url_for('blog.tag',id=tag.id) }}">{{ tag.title[:35] }}</a>
                    {% endfor %}
                </div>
            </div>


        </div>

        <main class="bd-content col-12 col-md-12 col-xl-9 py-md-3 ">
            {% with messages=get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category,message in messages %}
                        <div class="alert alert-{{ category }}" role="alert">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            {% block body %}
            {% endblock %}
        </main>

    </div>
</div>
{% block js %}
{% endblock %}
</body>
</html>

webapp/templates/blog/edit_article.html
{% extends "blog/edit_base.html" %}

{% block content %}
    <div class="form-group">
        {{ form.text.label() }}
        {{ form.text(id='editor',class="form-control",rows=5) }}
        {% if form.text.errors %}
            {% for e in form.text.errors %}
                <small class="form-text text-muted">{{ e }}</small>
            {% endfor %}
        {% endif %}
    </div>
{% endblock %}
{% block js %}
    <script src="https://cdn.ckeditor.com/ckeditor5/1.0.0-alpha.1/classic/ckeditor.js"></script>
    <script>
        ClassicEditor.create(document.querySelector('#editor'))
    </script>
{% endblock %}

webapp/templates/blog/list.html
{% import 'article.html' as article %}
{% extends "blog/base.html" %}
{% block title %}列表{% endblock %}
{% block body %}

    <ul class="nav nav-pills">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">排序</a>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="{{ url_for('blog.list',order='read',type=type,page=1,count=count) }}">热度</a>
          <a class="dropdown-item" href="{{ url_for('blog.list',order='update_date',type=type,page=1,count=count) }}">更新</a>
          <a class="dropdown-item" href="{{ url_for('blog.list',order='publish_date',type=type,page=1,count=count) }}">发布</a>
        </div>
      </li>
       <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">类型</a>
        <div class="dropdown-menu">
        	<a class="dropdown-item" href="{{ url_for('blog.list',order=order,type='all',page=1,count=count) }}">全部</a>
          <a class="dropdown-item" href="{{ url_for('blog.list',order=order,type='video',page=1,count=count) }}">视频</a>
          <a class="dropdown-item" href="{{ url_for('blog.list',order=order,type='photo',page=1,count=count) }}">图片</a>
          <a class="dropdown-item" href="{{ url_for('blog.list',order=order,type='article',page=1,count=count) }}">文章</a>
        </div>
      </li>
    </ul>
    <div class="mt-2 mb-3">
        {{ article.articleList(page.items) }}
    </div>
    <nav aria-label="Page navigation example">
      <ul class="pagination justify-content-center">
        <li class="page-item {% if not page.has_prev %}disabled{% endif %}">
          <a class="page-link" href="{{ url_for('blog.list',order=order,type=type,page=page.page-1,count=count) }}" tabindex="-1"><</a>
        </li>
        {% if page.pages>7 %}
            {% if page.page>2 %}
                <li class="page-item"><a class="page-link" href="{{ url_for('blog.list',order=order,type=type,page=1,count=count) }}">{{ 1 }}</a></li>
            {% endif %}
            {% for i in [-1,0,1] %}
                {% if page.page+i<=page.pages and page.page+i>=1 %}
                    <li class="page-item {% if page.page+i==page.page %}active{% endif %}"><a class="page-link" href="{{ url_for('blog.list',order=order,type=type,page=page.page+i,count=count) }}">{{ page.page+i }}</a></li>
                {% endif %}
            {% endfor %}
            {% if page.page<page.pages-1 %}
                <li class="page-item"><a class="page-link" href="{{ url_for('blog.list',order=order,type=type,page=page.pages,count=count) }}">{{ page.pages }}</a></li>
            {% endif %}
        {% else %}
            {% for item in range(page.pages) %}
            <li class="page-item"><a class="page-link" href="{{ url_for('blog.list',order=order,type=type,page=item+1,count=count) }}">{{ item+1 }}</a></li>
            {% endfor %}
        {% endif %}
        <li class="page-item  {% if not page.has_next %}disabled{% endif %}">
          <a class="page-link" href="{{ url_for('blog.list',order=order,type=type,page=page.page+1,count=count) }}">></a>
        </li>
      </ul>
    </nav>

{% endblock %}

webapp/templates/blog/search.html
{% import 'article.html' as article %}
{% extends "blog/base.html" %}
{% block title %}搜索{% endblock %}
{% block body %}
   {{ article.articleList(posts) }}
{% endblock %}

webapp/templates/blog/user_posts.html
{% import 'article.html' as article %}
{% extends "blog/base.html" %}
{% block title %}列表{% endblock %}
{% block body %}
    <img src="{{ user.head }}">
    <h2>{{ user.nickname or user.username }}</h2>
    <ul class="nav nav-pills">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">排序</a>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="{{ url_for('blog.user_posts',userid=user.id,order='read',type=type,page=1,count=count) }}">热度</a>
          <a class="dropdown-item" href="{{ url_for('blog.user_posts',userid=user.id,order='update_date',type=type,page=1,count=count) }}">更新</a>
          <a class="dropdown-item" href="{{ url_for('blog.user_posts',userid=user.id,order='publish_date',type=type,page=1,count=count) }}">发布</a>
        </div>
      </li>
       <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">类型</a>
        <div class="dropdown-menu">
        	<a class="dropdown-item" href="{{ url_for('blog.user_posts',userid=user.id,order=order,type='all',page=1,count=count) }}">全部</a>
          <a class="dropdown-item" href="{{ url_for('blog.user_posts',userid=user.id,order=order,type='video',page=1,count=count) }}">视频</a>
          <a class="dropdown-item" href="{{ url_for('blog.user_posts',userid=user.id,order=order,type='photo',page=1,count=count) }}">图片</a>
          <a class="dropdown-item" href="{{ url_for('blog.user_posts',userid=user.id,order=order,type='article',page=1,count=count) }}">文章</a>
        </div>
      </li>
    </ul>
    <div class="mt-2 mb-3">
        {{ article.articleList(page.items) }}
    </div>
    <nav aria-label="Page navigation example">
      <ul class="pagination justify-content-center">
        <li class="page-item {% if not page.has_prev %}disabled{% endif %}">
          <a class="page-link" href="{{ url_for('blog.user_posts',userid=user.id,order=order,type=type,page=page.page-1,count=count) }}" tabindex="-1"><</a>
        </li>
        {% if page.pages>7 %}
            {% if page.page>2 %}
                <li class="page-item"><a class="page-link" href="{{ url_for('blog.user_posts',userid=user.id,order=order,type=type,page=1,count=count) }}">{{ 1 }}</a></li>
            {% endif %}
            {% for i in [-1,0,1] %}
                {% if page.page+i<=page.pages and page.page+i>=1 %}
                    <li class="page-item {% if page.page+i==page.page %}active{% endif %}"><a class="page-link" href="{{ url_for('blog.user_posts',userid=user.id,order=order,type=type,page=page.page+i,count=count) }}">{{ page.page+i }}</a></li>
                {% endif %}
            {% endfor %}
            {% if page.page<page.pages-1 %}
                <li class="page-item"><a class="page-link" href="{{ url_for('blog.user_posts',userid=user.id,order=order,type=type,page=page.pages,count=count) }}">{{ page.pages }}</a></li>
            {% endif %}
        {% else %}
            {% for item in range(page.pages) %}
            <li class="page-item"><a class="page-link" href="{{ url_for('blog.user_posts',userid=user.id,order=order,type=type,page=item+1,count=count) }}">{{ item+1 }}</a></li>
            {% endfor %}
        {% endif %}
        <li class="page-item  {% if not page.has_next %}disabled{% endif %}">
          <a class="page-link" href="{{ url_for('blog.user_posts',userid=user.id,order=order,type=type,page=page.page+1,count=count) }}">></a>
        </li>
      </ul>
    </nav>

{% endblock %}